//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnboardingDifferentialReportToCsv.DB
{
    using System;
    
    public partial class EmplyeeDeptReport
    {
        public string Employee_ID { get; set; }
        public string Dept_Code { get; set; }
        public string Emp_Start_Status { get; set; }
        public string Emp_End_Status { get; set; }
    }
}
