//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnboardingDifferentialReportToCsv.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OnboardingOffboardingEntities : DbContext
    {
        public OnboardingOffboardingEntities()
            : base("name=OnboardingOffboardingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<EmplyeeDeptReport> PROC_EmployeeDeptDifferential(Nullable<System.DateTime> s1, Nullable<System.DateTime> e1)
        {
            var s1Parameter = s1.HasValue ?
                new ObjectParameter("s1", s1) :
                new ObjectParameter("s1", typeof(System.DateTime));
    
            var e1Parameter = e1.HasValue ?
                new ObjectParameter("e1", e1) :
                new ObjectParameter("e1", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EmplyeeDeptReport>("PROC_EmployeeDeptDifferential", s1Parameter, e1Parameter);
        }
    }
}
