#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnboardingOffboarding.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="OnboardingOffboarding")]
	public partial class OnboardingOffboardingDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBatchLog(BatchLog instance);
    partial void UpdateBatchLog(BatchLog instance);
    partial void DeleteBatchLog(BatchLog instance);
    partial void InsertOrg(Org instance);
    partial void UpdateOrg(Org instance);
    partial void DeleteOrg(Org instance);
    partial void InsertEmployee(Employee instance);
    partial void UpdateEmployee(Employee instance);
    partial void DeleteEmployee(Employee instance);
    partial void InsertEmployeeOrg(EmployeeOrg instance);
    partial void UpdateEmployeeOrg(EmployeeOrg instance);
    partial void DeleteEmployeeOrg(EmployeeOrg instance);
    partial void InsertEmployeeOrgReplay(EmployeeOrgReplay instance);
    partial void UpdateEmployeeOrgReplay(EmployeeOrgReplay instance);
    partial void DeleteEmployeeOrgReplay(EmployeeOrgReplay instance);
    #endregion
		
		public OnboardingOffboardingDataContext() : 
				base(global::OnboardingOffboarding.Properties.Settings.Default.OnboardingOffboardingConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public OnboardingOffboardingDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OnboardingOffboardingDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OnboardingOffboardingDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OnboardingOffboardingDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BatchLog> BatchLogs
		{
			get
			{
				return this.GetTable<BatchLog>();
			}
		}
		
		public System.Data.Linq.Table<Org> Orgs
		{
			get
			{
				return this.GetTable<Org>();
			}
		}
		
		public System.Data.Linq.Table<Employee> Employees
		{
			get
			{
				return this.GetTable<Employee>();
			}
		}
		
		public System.Data.Linq.Table<EmployeeOrg> EmployeeOrgs
		{
			get
			{
				return this.GetTable<EmployeeOrg>();
			}
		}
		
		public System.Data.Linq.Table<EmployeeOrgReplay> EmployeeOrgReplays
		{
			get
			{
				return this.GetTable<EmployeeOrgReplay>();
			}
		}
		
		public System.Data.Linq.Table<HrEmployeeHistoryForValidOrg> HrEmployeeHistoryForValidOrgs
		{
			get
			{
				return this.GetTable<HrEmployeeHistoryForValidOrg>();
			}
		}
		
		public System.Data.Linq.Table<HrUniqueEmployeesForValidOrg> HrUniqueEmployeesForValidOrgs
		{
			get
			{
				return this.GetTable<HrUniqueEmployeesForValidOrg>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteAllHistoryReplayData")]
		public int DeleteAllHistoryReplayData()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetEmployeeOrgReport")]
		public ISingleResult<GetEmployeeOrgReportResult> GetEmployeeOrgReport([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> start, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> end)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), start, end);
			return ((ISingleResult<GetEmployeeOrgReportResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetEmployeeOrgReplayReport")]
		public ISingleResult<GetEmployeeOrgReplayReportResult> GetEmployeeOrgReplayReport([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> start, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> end)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), start, end);
			return ((ISingleResult<GetEmployeeOrgReplayReportResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateEmployeeOrgDataFromHrSnapshotData")]
		public int UpdateEmployeeOrgDataFromHrSnapshotData()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateEmployeesFromHrData")]
		public int UpdateEmployeesFromHrData()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BatchLog")]
	public partial class BatchLog : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.DateTime _LogDateTime;
		
		private int _Status;
		
		private string _Message;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnLogDateTimeChanging(System.DateTime value);
    partial void OnLogDateTimeChanged();
    partial void OnStatusChanging(int value);
    partial void OnStatusChanged();
    partial void OnMessageChanging(string value);
    partial void OnMessageChanged();
    #endregion
		
		public BatchLog()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogDateTime", DbType="DateTime NOT NULL")]
		public System.DateTime LogDateTime
		{
			get
			{
				return this._LogDateTime;
			}
			set
			{
				if ((this._LogDateTime != value))
				{
					this.OnLogDateTimeChanging(value);
					this.SendPropertyChanging();
					this._LogDateTime = value;
					this.SendPropertyChanged("LogDateTime");
					this.OnLogDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int NOT NULL")]
		public int Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message", DbType="NVarChar(MAX)")]
		public string Message
		{
			get
			{
				return this._Message;
			}
			set
			{
				if ((this._Message != value))
				{
					this.OnMessageChanging(value);
					this.SendPropertyChanging();
					this._Message = value;
					this.SendPropertyChanged("Message");
					this.OnMessageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Org")]
	public partial class Org : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Name;
		
		private string _Source;
		
		private EntitySet<EmployeeOrg> _EmployeeOrgs;
		
		private EntitySet<EmployeeOrgReplay> _EmployeeOrgReplays;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnSourceChanging(string value);
    partial void OnSourceChanged();
    #endregion
		
		public Org()
		{
			this._EmployeeOrgs = new EntitySet<EmployeeOrg>(new Action<EmployeeOrg>(this.attach_EmployeeOrgs), new Action<EmployeeOrg>(this.detach_EmployeeOrgs));
			this._EmployeeOrgReplays = new EntitySet<EmployeeOrgReplay>(new Action<EmployeeOrgReplay>(this.attach_EmployeeOrgReplays), new Action<EmployeeOrgReplay>(this.detach_EmployeeOrgReplays));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(255)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Source", DbType="VarChar(255)")]
		public string Source
		{
			get
			{
				return this._Source;
			}
			set
			{
				if ((this._Source != value))
				{
					this.OnSourceChanging(value);
					this.SendPropertyChanging();
					this._Source = value;
					this.SendPropertyChanged("Source");
					this.OnSourceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Org_EmployeeOrg", Storage="_EmployeeOrgs", ThisKey="Id", OtherKey="OrgId")]
		public EntitySet<EmployeeOrg> EmployeeOrgs
		{
			get
			{
				return this._EmployeeOrgs;
			}
			set
			{
				this._EmployeeOrgs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Org_EmployeeOrgReplay", Storage="_EmployeeOrgReplays", ThisKey="Id", OtherKey="OrgId")]
		public EntitySet<EmployeeOrgReplay> EmployeeOrgReplays
		{
			get
			{
				return this._EmployeeOrgReplays;
			}
			set
			{
				this._EmployeeOrgReplays.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_EmployeeOrgs(EmployeeOrg entity)
		{
			this.SendPropertyChanging();
			entity.Org = this;
		}
		
		private void detach_EmployeeOrgs(EmployeeOrg entity)
		{
			this.SendPropertyChanging();
			entity.Org = null;
		}
		
		private void attach_EmployeeOrgReplays(EmployeeOrgReplay entity)
		{
			this.SendPropertyChanging();
			entity.Org = this;
		}
		
		private void detach_EmployeeOrgReplays(EmployeeOrgReplay entity)
		{
			this.SendPropertyChanging();
			entity.Org = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Employee")]
	public partial class Employee : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _NetId;
		
		private System.Nullable<int> _RcpId;
		
		private string _Lastname;
		
		private string _Firstname;
		
		private System.DateTime _DateTimeCreated;
		
		private System.Nullable<System.DateTime> _DateTimeUpdated;
		
		private EntitySet<EmployeeOrg> _EmployeeOrgs;
		
		private EntitySet<EmployeeOrgReplay> _EmployeeOrgReplays;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNetIdChanging(string value);
    partial void OnNetIdChanged();
    partial void OnRcpIdChanging(System.Nullable<int> value);
    partial void OnRcpIdChanged();
    partial void OnLastnameChanging(string value);
    partial void OnLastnameChanged();
    partial void OnFirstnameChanging(string value);
    partial void OnFirstnameChanged();
    partial void OnDateTimeCreatedChanging(System.DateTime value);
    partial void OnDateTimeCreatedChanged();
    partial void OnDateTimeUpdatedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateTimeUpdatedChanged();
    #endregion
		
		public Employee()
		{
			this._EmployeeOrgs = new EntitySet<EmployeeOrg>(new Action<EmployeeOrg>(this.attach_EmployeeOrgs), new Action<EmployeeOrg>(this.detach_EmployeeOrgs));
			this._EmployeeOrgReplays = new EntitySet<EmployeeOrgReplay>(new Action<EmployeeOrgReplay>(this.attach_EmployeeOrgReplays), new Action<EmployeeOrgReplay>(this.detach_EmployeeOrgReplays));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NetId", DbType="VarChar(50)")]
		public string NetId
		{
			get
			{
				return this._NetId;
			}
			set
			{
				if ((this._NetId != value))
				{
					this.OnNetIdChanging(value);
					this.SendPropertyChanging();
					this._NetId = value;
					this.SendPropertyChanged("NetId");
					this.OnNetIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RcpId", DbType="Int")]
		public System.Nullable<int> RcpId
		{
			get
			{
				return this._RcpId;
			}
			set
			{
				if ((this._RcpId != value))
				{
					this.OnRcpIdChanging(value);
					this.SendPropertyChanging();
					this._RcpId = value;
					this.SendPropertyChanged("RcpId");
					this.OnRcpIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lastname", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Lastname
		{
			get
			{
				return this._Lastname;
			}
			set
			{
				if ((this._Lastname != value))
				{
					this.OnLastnameChanging(value);
					this.SendPropertyChanging();
					this._Lastname = value;
					this.SendPropertyChanged("Lastname");
					this.OnLastnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Firstname", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Firstname
		{
			get
			{
				return this._Firstname;
			}
			set
			{
				if ((this._Firstname != value))
				{
					this.OnFirstnameChanging(value);
					this.SendPropertyChanging();
					this._Firstname = value;
					this.SendPropertyChanged("Firstname");
					this.OnFirstnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateTimeCreated", DbType="DateTime NOT NULL")]
		public System.DateTime DateTimeCreated
		{
			get
			{
				return this._DateTimeCreated;
			}
			set
			{
				if ((this._DateTimeCreated != value))
				{
					this.OnDateTimeCreatedChanging(value);
					this.SendPropertyChanging();
					this._DateTimeCreated = value;
					this.SendPropertyChanged("DateTimeCreated");
					this.OnDateTimeCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateTimeUpdated", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateTimeUpdated
		{
			get
			{
				return this._DateTimeUpdated;
			}
			set
			{
				if ((this._DateTimeUpdated != value))
				{
					this.OnDateTimeUpdatedChanging(value);
					this.SendPropertyChanging();
					this._DateTimeUpdated = value;
					this.SendPropertyChanged("DateTimeUpdated");
					this.OnDateTimeUpdatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Employee_EmployeeOrg", Storage="_EmployeeOrgs", ThisKey="Id", OtherKey="EmployeeId")]
		public EntitySet<EmployeeOrg> EmployeeOrgs
		{
			get
			{
				return this._EmployeeOrgs;
			}
			set
			{
				this._EmployeeOrgs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Employee_EmployeeOrgReplay", Storage="_EmployeeOrgReplays", ThisKey="Id", OtherKey="EmployeeId")]
		public EntitySet<EmployeeOrgReplay> EmployeeOrgReplays
		{
			get
			{
				return this._EmployeeOrgReplays;
			}
			set
			{
				this._EmployeeOrgReplays.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_EmployeeOrgs(EmployeeOrg entity)
		{
			this.SendPropertyChanging();
			entity.Employee = this;
		}
		
		private void detach_EmployeeOrgs(EmployeeOrg entity)
		{
			this.SendPropertyChanging();
			entity.Employee = null;
		}
		
		private void attach_EmployeeOrgReplays(EmployeeOrgReplay entity)
		{
			this.SendPropertyChanging();
			entity.Employee = this;
		}
		
		private void detach_EmployeeOrgReplays(EmployeeOrgReplay entity)
		{
			this.SendPropertyChanging();
			entity.Employee = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EmployeeOrg")]
	public partial class EmployeeOrg : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _EmployeeId;
		
		private int _OrgId;
		
		private System.DateTime _BeginDateTime;
		
		private System.Nullable<System.DateTime> _EndDateTime;
		
		private System.DateTime _HrBeginDateTime;
		
		private System.Nullable<System.DateTime> _HrEndDateTime;
		
		private EntityRef<Employee> _Employee;
		
		private EntityRef<Org> _Org;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnEmployeeIdChanging(int value);
    partial void OnEmployeeIdChanged();
    partial void OnOrgIdChanging(int value);
    partial void OnOrgIdChanged();
    partial void OnBeginDateTimeChanging(System.DateTime value);
    partial void OnBeginDateTimeChanged();
    partial void OnEndDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnEndDateTimeChanged();
    partial void OnHrBeginDateTimeChanging(System.DateTime value);
    partial void OnHrBeginDateTimeChanged();
    partial void OnHrEndDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnHrEndDateTimeChanged();
    #endregion
		
		public EmployeeOrg()
		{
			this._Employee = default(EntityRef<Employee>);
			this._Org = default(EntityRef<Org>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeId", DbType="Int NOT NULL")]
		public int EmployeeId
		{
			get
			{
				return this._EmployeeId;
			}
			set
			{
				if ((this._EmployeeId != value))
				{
					if (this._Employee.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEmployeeIdChanging(value);
					this.SendPropertyChanging();
					this._EmployeeId = value;
					this.SendPropertyChanged("EmployeeId");
					this.OnEmployeeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrgId", DbType="Int NOT NULL")]
		public int OrgId
		{
			get
			{
				return this._OrgId;
			}
			set
			{
				if ((this._OrgId != value))
				{
					if (this._Org.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnOrgIdChanging(value);
					this.SendPropertyChanging();
					this._OrgId = value;
					this.SendPropertyChanged("OrgId");
					this.OnOrgIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BeginDateTime", DbType="DateTime NOT NULL")]
		public System.DateTime BeginDateTime
		{
			get
			{
				return this._BeginDateTime;
			}
			set
			{
				if ((this._BeginDateTime != value))
				{
					this.OnBeginDateTimeChanging(value);
					this.SendPropertyChanging();
					this._BeginDateTime = value;
					this.SendPropertyChanged("BeginDateTime");
					this.OnBeginDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> EndDateTime
		{
			get
			{
				return this._EndDateTime;
			}
			set
			{
				if ((this._EndDateTime != value))
				{
					this.OnEndDateTimeChanging(value);
					this.SendPropertyChanging();
					this._EndDateTime = value;
					this.SendPropertyChanged("EndDateTime");
					this.OnEndDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HrBeginDateTime", DbType="DateTime NOT NULL")]
		public System.DateTime HrBeginDateTime
		{
			get
			{
				return this._HrBeginDateTime;
			}
			set
			{
				if ((this._HrBeginDateTime != value))
				{
					this.OnHrBeginDateTimeChanging(value);
					this.SendPropertyChanging();
					this._HrBeginDateTime = value;
					this.SendPropertyChanged("HrBeginDateTime");
					this.OnHrBeginDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HrEndDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> HrEndDateTime
		{
			get
			{
				return this._HrEndDateTime;
			}
			set
			{
				if ((this._HrEndDateTime != value))
				{
					this.OnHrEndDateTimeChanging(value);
					this.SendPropertyChanging();
					this._HrEndDateTime = value;
					this.SendPropertyChanged("HrEndDateTime");
					this.OnHrEndDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Employee_EmployeeOrg", Storage="_Employee", ThisKey="EmployeeId", OtherKey="Id", IsForeignKey=true)]
		public Employee Employee
		{
			get
			{
				return this._Employee.Entity;
			}
			set
			{
				Employee previousValue = this._Employee.Entity;
				if (((previousValue != value) 
							|| (this._Employee.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Employee.Entity = null;
						previousValue.EmployeeOrgs.Remove(this);
					}
					this._Employee.Entity = value;
					if ((value != null))
					{
						value.EmployeeOrgs.Add(this);
						this._EmployeeId = value.Id;
					}
					else
					{
						this._EmployeeId = default(int);
					}
					this.SendPropertyChanged("Employee");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Org_EmployeeOrg", Storage="_Org", ThisKey="OrgId", OtherKey="Id", IsForeignKey=true)]
		public Org Org
		{
			get
			{
				return this._Org.Entity;
			}
			set
			{
				Org previousValue = this._Org.Entity;
				if (((previousValue != value) 
							|| (this._Org.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Org.Entity = null;
						previousValue.EmployeeOrgs.Remove(this);
					}
					this._Org.Entity = value;
					if ((value != null))
					{
						value.EmployeeOrgs.Add(this);
						this._OrgId = value.Id;
					}
					else
					{
						this._OrgId = default(int);
					}
					this.SendPropertyChanged("Org");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EmployeeOrgReplay")]
	public partial class EmployeeOrgReplay : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _EmployeeId;
		
		private int _OrgId;
		
		private System.DateTime _BeginDateTime;
		
		private System.Nullable<System.DateTime> _EndDateTime;
		
		private EntityRef<Employee> _Employee;
		
		private EntityRef<Org> _Org;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnEmployeeIdChanging(int value);
    partial void OnEmployeeIdChanged();
    partial void OnOrgIdChanging(int value);
    partial void OnOrgIdChanged();
    partial void OnBeginDateTimeChanging(System.DateTime value);
    partial void OnBeginDateTimeChanged();
    partial void OnEndDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnEndDateTimeChanged();
    #endregion
		
		public EmployeeOrgReplay()
		{
			this._Employee = default(EntityRef<Employee>);
			this._Org = default(EntityRef<Org>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeId", DbType="Int NOT NULL")]
		public int EmployeeId
		{
			get
			{
				return this._EmployeeId;
			}
			set
			{
				if ((this._EmployeeId != value))
				{
					if (this._Employee.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEmployeeIdChanging(value);
					this.SendPropertyChanging();
					this._EmployeeId = value;
					this.SendPropertyChanged("EmployeeId");
					this.OnEmployeeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrgId", DbType="Int NOT NULL")]
		public int OrgId
		{
			get
			{
				return this._OrgId;
			}
			set
			{
				if ((this._OrgId != value))
				{
					if (this._Org.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnOrgIdChanging(value);
					this.SendPropertyChanging();
					this._OrgId = value;
					this.SendPropertyChanged("OrgId");
					this.OnOrgIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BeginDateTime", DbType="DateTime NOT NULL")]
		public System.DateTime BeginDateTime
		{
			get
			{
				return this._BeginDateTime;
			}
			set
			{
				if ((this._BeginDateTime != value))
				{
					this.OnBeginDateTimeChanging(value);
					this.SendPropertyChanging();
					this._BeginDateTime = value;
					this.SendPropertyChanged("BeginDateTime");
					this.OnBeginDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> EndDateTime
		{
			get
			{
				return this._EndDateTime;
			}
			set
			{
				if ((this._EndDateTime != value))
				{
					this.OnEndDateTimeChanging(value);
					this.SendPropertyChanging();
					this._EndDateTime = value;
					this.SendPropertyChanged("EndDateTime");
					this.OnEndDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Employee_EmployeeOrgReplay", Storage="_Employee", ThisKey="EmployeeId", OtherKey="Id", IsForeignKey=true)]
		public Employee Employee
		{
			get
			{
				return this._Employee.Entity;
			}
			set
			{
				Employee previousValue = this._Employee.Entity;
				if (((previousValue != value) 
							|| (this._Employee.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Employee.Entity = null;
						previousValue.EmployeeOrgReplays.Remove(this);
					}
					this._Employee.Entity = value;
					if ((value != null))
					{
						value.EmployeeOrgReplays.Add(this);
						this._EmployeeId = value.Id;
					}
					else
					{
						this._EmployeeId = default(int);
					}
					this.SendPropertyChanged("Employee");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Org_EmployeeOrgReplay", Storage="_Org", ThisKey="OrgId", OtherKey="Id", IsForeignKey=true)]
		public Org Org
		{
			get
			{
				return this._Org.Entity;
			}
			set
			{
				Org previousValue = this._Org.Entity;
				if (((previousValue != value) 
							|| (this._Org.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Org.Entity = null;
						previousValue.EmployeeOrgReplays.Remove(this);
					}
					this._Org.Entity = value;
					if ((value != null))
					{
						value.EmployeeOrgReplays.Add(this);
						this._OrgId = value.Id;
					}
					else
					{
						this._OrgId = default(int);
					}
					this.SendPropertyChanged("Org");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HrEmployeeHistoryForValidOrgs")]
	public partial class HrEmployeeHistoryForValidOrg
	{
		
		private string _EMPLOYEE_ID;
		
		private System.Nullable<decimal> _APPT_NO;
		
		private System.Nullable<System.DateTime> _EFFDT;
		
		private string _DEPT_CODE;
		
		private string _DEPT_DESCR;
		
		private string _EMPLOYEE_NAME;
		
		private string _NETID;
		
		private System.Nullable<decimal> _RCP_ID;
		
		private string _ASSIGNMENT_STATUS_CODE;
		
		private string _EMPLOYEE_TYPE_CODE;
		
		private System.Nullable<System.DateTime> _JOB_BEGIN_DT;
		
		private System.Nullable<System.DateTime> _APPT_BEGIN_DT;
		
		private System.Nullable<System.DateTime> _APPT_END_DT;
		
		private System.Nullable<System.DateTime> _SEPARATION_DATE;
		
		private string _SEPARATION_CODE;
		
		private string _SEPARATION_DESCR;
		
		private System.Nullable<System.DateTime> _LAST_DATE_WORKED;
		
		private string _PAYGROUP;
		
		private string _JOB_CLASS;
		
		private System.Nullable<System.DateTime> _EFFECTIVE_START_DT;
		
		private System.Nullable<System.DateTime> _EFFECTIVE_END_DT;
		
		public HrEmployeeHistoryForValidOrg()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMPLOYEE_ID", DbType="VarChar(11)")]
		public string EMPLOYEE_ID
		{
			get
			{
				return this._EMPLOYEE_ID;
			}
			set
			{
				if ((this._EMPLOYEE_ID != value))
				{
					this._EMPLOYEE_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APPT_NO", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> APPT_NO
		{
			get
			{
				return this._APPT_NO;
			}
			set
			{
				if ((this._APPT_NO != value))
				{
					this._APPT_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EFFDT", DbType="DateTime")]
		public System.Nullable<System.DateTime> EFFDT
		{
			get
			{
				return this._EFFDT;
			}
			set
			{
				if ((this._EFFDT != value))
				{
					this._EFFDT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_CODE", DbType="VarChar(10)")]
		public string DEPT_CODE
		{
			get
			{
				return this._DEPT_CODE;
			}
			set
			{
				if ((this._DEPT_CODE != value))
				{
					this._DEPT_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_DESCR", DbType="VarChar(30)")]
		public string DEPT_DESCR
		{
			get
			{
				return this._DEPT_DESCR;
			}
			set
			{
				if ((this._DEPT_DESCR != value))
				{
					this._DEPT_DESCR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMPLOYEE_NAME", DbType="VarChar(50)")]
		public string EMPLOYEE_NAME
		{
			get
			{
				return this._EMPLOYEE_NAME;
			}
			set
			{
				if ((this._EMPLOYEE_NAME != value))
				{
					this._EMPLOYEE_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NETID", DbType="VarChar(30)")]
		public string NETID
		{
			get
			{
				return this._NETID;
			}
			set
			{
				if ((this._NETID != value))
				{
					this._NETID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RCP_ID", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> RCP_ID
		{
			get
			{
				return this._RCP_ID;
			}
			set
			{
				if ((this._RCP_ID != value))
				{
					this._RCP_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ASSIGNMENT_STATUS_CODE", DbType="VarChar(1)")]
		public string ASSIGNMENT_STATUS_CODE
		{
			get
			{
				return this._ASSIGNMENT_STATUS_CODE;
			}
			set
			{
				if ((this._ASSIGNMENT_STATUS_CODE != value))
				{
					this._ASSIGNMENT_STATUS_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMPLOYEE_TYPE_CODE", DbType="VarChar(3)")]
		public string EMPLOYEE_TYPE_CODE
		{
			get
			{
				return this._EMPLOYEE_TYPE_CODE;
			}
			set
			{
				if ((this._EMPLOYEE_TYPE_CODE != value))
				{
					this._EMPLOYEE_TYPE_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JOB_BEGIN_DT", DbType="DateTime")]
		public System.Nullable<System.DateTime> JOB_BEGIN_DT
		{
			get
			{
				return this._JOB_BEGIN_DT;
			}
			set
			{
				if ((this._JOB_BEGIN_DT != value))
				{
					this._JOB_BEGIN_DT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APPT_BEGIN_DT", DbType="DateTime")]
		public System.Nullable<System.DateTime> APPT_BEGIN_DT
		{
			get
			{
				return this._APPT_BEGIN_DT;
			}
			set
			{
				if ((this._APPT_BEGIN_DT != value))
				{
					this._APPT_BEGIN_DT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APPT_END_DT", DbType="DateTime")]
		public System.Nullable<System.DateTime> APPT_END_DT
		{
			get
			{
				return this._APPT_END_DT;
			}
			set
			{
				if ((this._APPT_END_DT != value))
				{
					this._APPT_END_DT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEPARATION_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> SEPARATION_DATE
		{
			get
			{
				return this._SEPARATION_DATE;
			}
			set
			{
				if ((this._SEPARATION_DATE != value))
				{
					this._SEPARATION_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEPARATION_CODE", DbType="VarChar(3)")]
		public string SEPARATION_CODE
		{
			get
			{
				return this._SEPARATION_CODE;
			}
			set
			{
				if ((this._SEPARATION_CODE != value))
				{
					this._SEPARATION_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEPARATION_DESCR", DbType="VarChar(50)")]
		public string SEPARATION_DESCR
		{
			get
			{
				return this._SEPARATION_DESCR;
			}
			set
			{
				if ((this._SEPARATION_DESCR != value))
				{
					this._SEPARATION_DESCR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_DATE_WORKED", DbType="DateTime")]
		public System.Nullable<System.DateTime> LAST_DATE_WORKED
		{
			get
			{
				return this._LAST_DATE_WORKED;
			}
			set
			{
				if ((this._LAST_DATE_WORKED != value))
				{
					this._LAST_DATE_WORKED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAYGROUP", DbType="VarChar(3)")]
		public string PAYGROUP
		{
			get
			{
				return this._PAYGROUP;
			}
			set
			{
				if ((this._PAYGROUP != value))
				{
					this._PAYGROUP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JOB_CLASS", DbType="VarChar(6)")]
		public string JOB_CLASS
		{
			get
			{
				return this._JOB_CLASS;
			}
			set
			{
				if ((this._JOB_CLASS != value))
				{
					this._JOB_CLASS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EFFECTIVE_START_DT", DbType="DateTime")]
		public System.Nullable<System.DateTime> EFFECTIVE_START_DT
		{
			get
			{
				return this._EFFECTIVE_START_DT;
			}
			set
			{
				if ((this._EFFECTIVE_START_DT != value))
				{
					this._EFFECTIVE_START_DT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EFFECTIVE_END_DT", DbType="DateTime")]
		public System.Nullable<System.DateTime> EFFECTIVE_END_DT
		{
			get
			{
				return this._EFFECTIVE_END_DT;
			}
			set
			{
				if ((this._EFFECTIVE_END_DT != value))
				{
					this._EFFECTIVE_END_DT = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HrUniqueEmployeesForValidOrgs")]
	public partial class HrUniqueEmployeesForValidOrg
	{
		
		private string _EMPLOYEE_ID;
		
		private string _NETID;
		
		private System.Nullable<decimal> _RCP_ID;
		
		private string _LAST_NAME;
		
		private string _FIRST_NAME;
		
		public HrUniqueEmployeesForValidOrg()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMPLOYEE_ID", DbType="VarChar(11)")]
		public string EMPLOYEE_ID
		{
			get
			{
				return this._EMPLOYEE_ID;
			}
			set
			{
				if ((this._EMPLOYEE_ID != value))
				{
					this._EMPLOYEE_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NETID", DbType="VarChar(30)")]
		public string NETID
		{
			get
			{
				return this._NETID;
			}
			set
			{
				if ((this._NETID != value))
				{
					this._NETID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RCP_ID", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> RCP_ID
		{
			get
			{
				return this._RCP_ID;
			}
			set
			{
				if ((this._RCP_ID != value))
				{
					this._RCP_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_NAME", DbType="VarChar(50)")]
		public string LAST_NAME
		{
			get
			{
				return this._LAST_NAME;
			}
			set
			{
				if ((this._LAST_NAME != value))
				{
					this._LAST_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIRST_NAME", DbType="VarChar(50)")]
		public string FIRST_NAME
		{
			get
			{
				return this._FIRST_NAME;
			}
			set
			{
				if ((this._FIRST_NAME != value))
				{
					this._FIRST_NAME = value;
				}
			}
		}
	}
	
	public partial class GetEmployeeOrgReportResult
	{
		
		private int _Id;
		
		private int _EmployeeId;
		
		private int _OrgId;
		
		private System.DateTime _BeginDateTime;
		
		private System.Nullable<System.DateTime> _EndDateTime;
		
		private string _OrgName;
		
		private string _EmployeeStatus;
		
		private int _Hire;
		
		public GetEmployeeOrgReportResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeId", DbType="Int NOT NULL")]
		public int EmployeeId
		{
			get
			{
				return this._EmployeeId;
			}
			set
			{
				if ((this._EmployeeId != value))
				{
					this._EmployeeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrgId", DbType="Int NOT NULL")]
		public int OrgId
		{
			get
			{
				return this._OrgId;
			}
			set
			{
				if ((this._OrgId != value))
				{
					this._OrgId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BeginDateTime", DbType="DateTime NOT NULL")]
		public System.DateTime BeginDateTime
		{
			get
			{
				return this._BeginDateTime;
			}
			set
			{
				if ((this._BeginDateTime != value))
				{
					this._BeginDateTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> EndDateTime
		{
			get
			{
				return this._EndDateTime;
			}
			set
			{
				if ((this._EndDateTime != value))
				{
					this._EndDateTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrgName", DbType="VarChar(255)")]
		public string OrgName
		{
			get
			{
				return this._OrgName;
			}
			set
			{
				if ((this._OrgName != value))
				{
					this._OrgName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeStatus", DbType="VarChar(22) NOT NULL", CanBeNull=false)]
		public string EmployeeStatus
		{
			get
			{
				return this._EmployeeStatus;
			}
			set
			{
				if ((this._EmployeeStatus != value))
				{
					this._EmployeeStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hire", DbType="Int NOT NULL")]
		public int Hire
		{
			get
			{
				return this._Hire;
			}
			set
			{
				if ((this._Hire != value))
				{
					this._Hire = value;
				}
			}
		}
	}
	
	public partial class GetEmployeeOrgReplayReportResult
	{
		
		private int _Id;
		
		private int _EmployeeId;
		
		private int _OrgId;
		
		private System.DateTime _BeginDateTime;
		
		private System.Nullable<System.DateTime> _EndDateTime;
		
		private string _OrgName;
		
		private string _EmployeeStatus;
		
		private int _Hire;
		
		public GetEmployeeOrgReplayReportResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeId", DbType="Int NOT NULL")]
		public int EmployeeId
		{
			get
			{
				return this._EmployeeId;
			}
			set
			{
				if ((this._EmployeeId != value))
				{
					this._EmployeeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrgId", DbType="Int NOT NULL")]
		public int OrgId
		{
			get
			{
				return this._OrgId;
			}
			set
			{
				if ((this._OrgId != value))
				{
					this._OrgId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BeginDateTime", DbType="DateTime NOT NULL")]
		public System.DateTime BeginDateTime
		{
			get
			{
				return this._BeginDateTime;
			}
			set
			{
				if ((this._BeginDateTime != value))
				{
					this._BeginDateTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> EndDateTime
		{
			get
			{
				return this._EndDateTime;
			}
			set
			{
				if ((this._EndDateTime != value))
				{
					this._EndDateTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrgName", DbType="VarChar(255)")]
		public string OrgName
		{
			get
			{
				return this._OrgName;
			}
			set
			{
				if ((this._OrgName != value))
				{
					this._OrgName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeStatus", DbType="VarChar(22) NOT NULL", CanBeNull=false)]
		public string EmployeeStatus
		{
			get
			{
				return this._EmployeeStatus;
			}
			set
			{
				if ((this._EmployeeStatus != value))
				{
					this._EmployeeStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hire", DbType="Int NOT NULL")]
		public int Hire
		{
			get
			{
				return this._Hire;
			}
			set
			{
				if ((this._Hire != value))
				{
					this._Hire = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
