CREATE TABLE [dbo].[test_HRI_NC_EMPLOYEES_HIST]
(
[EMPLOYEE_ID] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[APPT_NO] [numeric] (38, 0) NULL,
[EFFDT] [datetime] NULL,
[DEPT_CODE] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEPT_DESCR] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPLOYEE_NAME] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NETID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RCP_ID] [numeric] (38, 0) NULL,
[ASSIGNMENT_STATUS_CODE] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPLOYEE_TYPE_CODE] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JOB_BEGIN_DT] [datetime] NULL,
[APPT_BEGIN_DT] [datetime] NULL,
[APPT_END_DT] [datetime] NULL,
[SEPARATION_DATE] [datetime] NULL,
[SEPARATION_CODE] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SEPARATION_DESCR] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LAST_DATE_WORKED] [datetime] NULL,
[PAYGROUP] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JOB_CLASS] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFFECTIVE_START_DT] [datetime] NULL,
[EFFECTIVE_END_DT] [datetime] NULL,
[ID] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[test_HRI_NC_EMPLOYEES_HIST] ADD CONSTRAINT [PK_test_HRI_NC_EMPLOYEES_HIST] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
